# Generated by Django 5.2.3 on 2025-06-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=255)),
                ('link', models.URLField(unique=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('time_ago', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
